
package pl.marganski.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Days2HolidaysService", targetNamespace = "http://soa.marganski.pl/", wsdlLocation = "http://localhost:8000/Counter/ToHolidays?wsdl")
public class Days2HolidaysService
    extends Service
{

    private final static URL DAYS2HOLIDAYSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAYS2HOLIDAYSSERVICE_EXCEPTION;
    private final static QName DAYS2HOLIDAYSSERVICE_QNAME = new QName("http://soa.marganski.pl/", "Days2HolidaysService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/Counter/ToHolidays?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAYS2HOLIDAYSSERVICE_WSDL_LOCATION = url;
        DAYS2HOLIDAYSSERVICE_EXCEPTION = e;
    }

    public Days2HolidaysService() {
        super(__getWsdlLocation(), DAYS2HOLIDAYSSERVICE_QNAME);
    }

    public Days2HolidaysService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAYS2HOLIDAYSSERVICE_QNAME, features);
    }

    public Days2HolidaysService(URL wsdlLocation) {
        super(wsdlLocation, DAYS2HOLIDAYSSERVICE_QNAME);
    }

    public Days2HolidaysService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAYS2HOLIDAYSSERVICE_QNAME, features);
    }

    public Days2HolidaysService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Days2HolidaysService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Days2Holidays
     */
    @WebEndpoint(name = "Days2HolidaysPort")
    public Days2Holidays getDays2HolidaysPort() {
        return super.getPort(new QName("http://soa.marganski.pl/", "Days2HolidaysPort"), Days2Holidays.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Days2Holidays
     */
    @WebEndpoint(name = "Days2HolidaysPort")
    public Days2Holidays getDays2HolidaysPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.marganski.pl/", "Days2HolidaysPort"), Days2Holidays.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAYS2HOLIDAYSSERVICE_EXCEPTION!= null) {
            throw DAYS2HOLIDAYSSERVICE_EXCEPTION;
        }
        return DAYS2HOLIDAYSSERVICE_WSDL_LOCATION;
    }

}
