
package pl.marganski.soa;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Days2Holidays", targetNamespace = "http://soa.marganski.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Days2Holidays {


    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDaysToHolidays", targetNamespace = "http://soa.marganski.pl/", className = "pl.marganski.soa.GetDaysToHolidays")
    @ResponseWrapper(localName = "getDaysToHolidaysResponse", targetNamespace = "http://soa.marganski.pl/", className = "pl.marganski.soa.GetDaysToHolidaysResponse")
    @Action(input = "http://soa.marganski.pl/Days2Holidays/getDaysToHolidaysRequest", output = "http://soa.marganski.pl/Days2Holidays/getDaysToHolidaysResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://soa.marganski.pl/Days2Holidays/getDaysToHolidays/Fault/ParseException")
    })
    public String getDaysToHolidays()
        throws ParseException_Exception
    ;

}
