
package pl.marganski.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExchangeOfficeService", targetNamespace = "http://soa.marganski.pl/", wsdlLocation = "http://localhost:8000/ExchangeOffice/exchanger?wsdl")
public class ExchangeOfficeService
    extends Service
{

    private final static URL EXCHANGEOFFICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCHANGEOFFICESERVICE_EXCEPTION;
    private final static QName EXCHANGEOFFICESERVICE_QNAME = new QName("http://soa.marganski.pl/", "ExchangeOfficeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/ExchangeOffice/exchanger?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCHANGEOFFICESERVICE_WSDL_LOCATION = url;
        EXCHANGEOFFICESERVICE_EXCEPTION = e;
    }

    public ExchangeOfficeService() {
        super(__getWsdlLocation(), EXCHANGEOFFICESERVICE_QNAME);
    }

    public ExchangeOfficeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCHANGEOFFICESERVICE_QNAME, features);
    }

    public ExchangeOfficeService(URL wsdlLocation) {
        super(wsdlLocation, EXCHANGEOFFICESERVICE_QNAME);
    }

    public ExchangeOfficeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCHANGEOFFICESERVICE_QNAME, features);
    }

    public ExchangeOfficeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeOfficeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExchangeOffice
     */
    @WebEndpoint(name = "ExchangeOfficePort")
    public ExchangeOffice getExchangeOfficePort() {
        return super.getPort(new QName("http://soa.marganski.pl/", "ExchangeOfficePort"), ExchangeOffice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeOffice
     */
    @WebEndpoint(name = "ExchangeOfficePort")
    public ExchangeOffice getExchangeOfficePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.marganski.pl/", "ExchangeOfficePort"), ExchangeOffice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCHANGEOFFICESERVICE_EXCEPTION!= null) {
            throw EXCHANGEOFFICESERVICE_EXCEPTION;
        }
        return EXCHANGEOFFICESERVICE_WSDL_LOCATION;
    }

}
