
package pl.marganski.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExchangeOffice", targetNamespace = "http://soa.marganski.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExchangeOffice {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sellCurrency", targetNamespace = "http://soa.marganski.pl/", className = "pl.marganski.soa.SellCurrency")
    @ResponseWrapper(localName = "sellCurrencyResponse", targetNamespace = "http://soa.marganski.pl/", className = "pl.marganski.soa.SellCurrencyResponse")
    @Action(input = "http://soa.marganski.pl/ExchangeOffice/sellCurrencyRequest", output = "http://soa.marganski.pl/ExchangeOffice/sellCurrencyResponse")
    public String sellCurrency(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrency", targetNamespace = "http://soa.marganski.pl/", className = "pl.marganski.soa.GetCurrency")
    @ResponseWrapper(localName = "getCurrencyResponse", targetNamespace = "http://soa.marganski.pl/", className = "pl.marganski.soa.GetCurrencyResponse")
    @Action(input = "http://soa.marganski.pl/ExchangeOffice/getCurrencyRequest", output = "http://soa.marganski.pl/ExchangeOffice/getCurrencyResponse")
    public String getCurrency(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
