
package pl.marganski.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StringExplorerService", targetNamespace = "http://soa.marganski.pl/", wsdlLocation = "http://localhost:8000/Explorer/StringExplorer?wsdl")
public class StringExplorerService
    extends Service
{

    private final static URL STRINGEXPLORERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STRINGEXPLORERSERVICE_EXCEPTION;
    private final static QName STRINGEXPLORERSERVICE_QNAME = new QName("http://soa.marganski.pl/", "StringExplorerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/Explorer/StringExplorer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STRINGEXPLORERSERVICE_WSDL_LOCATION = url;
        STRINGEXPLORERSERVICE_EXCEPTION = e;
    }

    public StringExplorerService() {
        super(__getWsdlLocation(), STRINGEXPLORERSERVICE_QNAME);
    }

    public StringExplorerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STRINGEXPLORERSERVICE_QNAME, features);
    }

    public StringExplorerService(URL wsdlLocation) {
        super(wsdlLocation, STRINGEXPLORERSERVICE_QNAME);
    }

    public StringExplorerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STRINGEXPLORERSERVICE_QNAME, features);
    }

    public StringExplorerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StringExplorerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StringExplorer
     */
    @WebEndpoint(name = "StringExplorerPort")
    public StringExplorer getStringExplorerPort() {
        return super.getPort(new QName("http://soa.marganski.pl/", "StringExplorerPort"), StringExplorer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringExplorer
     */
    @WebEndpoint(name = "StringExplorerPort")
    public StringExplorer getStringExplorerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.marganski.pl/", "StringExplorerPort"), StringExplorer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STRINGEXPLORERSERVICE_EXCEPTION!= null) {
            throw STRINGEXPLORERSERVICE_EXCEPTION;
        }
        return STRINGEXPLORERSERVICE_WSDL_LOCATION;
    }

}
